In [72]:
from scipy.spatial.transform import Rotation as R
import numpy as np

In [78]:
r = R.from_quat([-0.7666340, -0.00617, -0.0059, 0.642027])
print(r.as_euler('xyz', degrees=True))
c2w = r.as_matrix()
w2c = np.linalg.inv(c2w)
print(R.from_matrix(w2c).as_euler('xyz', degrees=True))

[-100.11111391   -0.97229344    0.10798071]
[ 1.00109649e+02 -6.43814978e-02  9.76149919e-01]


In [87]:
cv2bd = np.array([[1,0,0],
              [0,-1,0],
              [0,0,-1]])

In [111]:

# right
r = R.from_quat([0.614598, -0.60624, 0.3555805, -0.35817])
c2w_cv = r.as_matrix()
print("CV:c2w\n")
print("XYZ->uvw, X, Y, Z")
print(R.from_matrix(c2w_cv).as_euler('xyz', degrees=True))
w2c_cv = np.linalg.inv(c2w_cv)
print("CV:w2c\n")
print(R.from_matrix(w2c_cv).as_euler('xyz', degrees=True))

w2c_bd = np.matmul(cv2bd, w2c_cv)
print("BD:w2c")
print(R.from_matrix(w2c_bd).as_euler('xyz', degrees=True))
c2w_bd = np.linalg.inv(w2c_bd)
print("YOU NEED TO TYPE IN Blender IN XYZ EULUER SETTING")
print(R.from_matrix(c2w_bd).as_euler('xyz', degrees=True))

CV:c2w

XYZ->uvw, X, Y, Z
[-119.37645557   -0.1606702   -89.30943743]
CV:w2c

[178.93407729 -60.61808879 -88.59239251]
BD:w2c
[-1.06592271 60.61808879 88.59239251]
[ 60.62354443  -0.1606702  -89.30943743]


In [112]:
# r = R.from_euler("xyz", [-0.7, 0, 0])
# front
r = R.from_quat([-0.7666340, -0.00617, -0.0059, 0.642027])
c2w_cv = r.as_matrix()
print("CV:c2w\n")
print("XYZ->uvw, X, Y, Z")
print(R.from_matrix(c2w_cv).as_euler('xyz', degrees=True))
w2c_cv = np.linalg.inv(c2w_cv)
print("CV:w2c\n")
print(R.from_matrix(w2c_cv).as_euler('xyz', degrees=True))

w2c_bd = np.matmul(cv2bd, w2c_cv)
print("BD:w2c")
print(R.from_matrix(w2c_bd).as_euler('xyz', degrees=True))
c2w_bd = np.linalg.inv(w2c_bd)
print("YOU NEED TO TYPE IN Blender IN XYZ EULUER SETTING")
print(R.from_matrix(c2w_bd).as_euler('xyz', degrees=True))

CV:c2w

XYZ->uvw, X, Y, Z
[-100.11111391   -0.97229344    0.10798071]
CV:w2c

[ 1.00109649e+02 -6.43814978e-02  9.76149919e-01]
BD:w2c
[-7.98903508e+01  6.43814978e-02 -9.76149919e-01]
YOU NEED TO TYPE IN Blender IN XYZ EULUER SETTING
[79.88888609 -0.97229344  0.10798071]


In [113]:
# left
r = R.from_quat([0.60853, 0.61367, -0.35937, -0.35206])
c2w_cv = r.as_matrix()
print("CV:c2w\n")
print("XYZ->uvw, X, Y, Z")
print(R.from_matrix(c2w_cv).as_euler('xyz', degrees=True))
w2c_cv = np.linalg.inv(c2w_cv)
print("CV:w2c\n")
print(R.from_matrix(w2c_cv).as_euler('xyz', degrees=True))

w2c_bd = np.matmul(cv2bd, w2c_cv)
print("BD:w2c")
print(R.from_matrix(w2c_bd).as_euler('xyz', degrees=True))
c2w_bd = np.linalg.inv(w2c_bd)
print("YOU NEED TO TYPE IN Blender IN XYZ EULUER SETTING")
print(R.from_matrix(c2w_bd).as_euler('xyz', degrees=True))

CV:c2w

XYZ->uvw, X, Y, Z
[-119.59177785    0.30238392   90.65793647]
CV:w2c

[-178.53939429   60.39809957   91.33200635]
BD:w2c
[  1.46060571 -60.39809957 -91.33200635]
YOU NEED TO TYPE IN Blender IN XYZ EULUER SETTING
[60.40822215  0.30238392 90.65793647]
